language: ruby
cache: bundler
rvm:
- 2.3.0
sudo: false
deploy:
  provider: rubygems
  gem:
    master: elbas
  on:
    repo: lserman/capistrano-elbas
    branch: master
  api_key:
    secure: ARM2JGEokm/TaJvIIwGgdL4s0QuMlwdVXzwtE4TwiqiSQO2yp8Eet9B0o55O3fITV2Z9UGUBF/9ymoKD2S4m/iGOARosj8q+gmgE/84fdF3glAqTtkCPsUZH8fseAH41e4XYwWkoRhwbxHBVhLn5rVGO4oJKWtFGnddacDBolFQ=
